name: Update Release Badges

on:
  release:
    types: [published]

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 jq locales
          sudo locale-gen id_ID.UTF-8

      - name: Run Python Script
        # Memanggil file python "update_badges.py"
        run: |
          python3 update_badges.py