name: Update Release Badge

on:
  release:
    types: [published]

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update README Badge
        run: |
          latest_release=$(jq -r .release.tag_name < "$GITHUB_EVENT_PATH")
          badge_url="https://img.shields.io/badge/Release-$latest_release-brightgreen?style=for-the-badge"
          sed -i "s|https://img.shields.io/github/v/release/mohammadfirmansyah/Edvisor?style=for-the-badge|$badge_url|g" README.md

      - name: Commit Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update release badge to $latest_release" || echo "No changes to commit"
          git push
