# .github/workflows/test-release-trigger.yml

name: Test Release Trigger

on:
  release:
    types: [published]

jobs:
  test-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Print Release Information
        run: |
          echo "Release tag: ${{ github.ref_name }}"
          echo "Published at: ${{ github.event.release.published_at }}"