# .github/workflows/update-release-badge.yml

name: Update Release Badges

on:
  release:
    types: [published]

permissions:
  contents: write  # Memberikan izin tulis pada konten repository

jobs:
  update-badges:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Mengambil seluruh history untuk push

      # 2. Setup Environment
      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y jq locales
          sudo locale-gen id_ID.UTF-8

      # 3. Extract Release Information
      - name: Extract Release Information
        id: extract_release
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_OUTPUT

          PUBLISHED_AT=$(jq -r .release.published_at "$GITHUB_EVENT_PATH")
          echo "PUBLISHED_AT=${PUBLISHED_AT}" >> $GITHUB_OUTPUT

      # 4. Debug: Cetak Payload Event
      - name: Print Event Payload
        run: cat "$GITHUB_EVENT_PATH"

      # 5. Format Release Date to Indonesian
      - name: Format Release Date
        id: format_date
        run: |
          PUBLISHED_AT=${{ steps.extract_release.outputs.PUBLISHED_AT }}
          if [ "$PUBLISHED_AT" = "null" ] || [ -z "$PUBLISHED_AT" ]; then
            echo "PUBLISHED_AT tidak tersedia. Workflow dihentikan."
            exit 1
          fi
          FORMATTED_DATE=$(LC_ALL=id_ID.UTF-8 date -d "$PUBLISHED_AT" +"%d %B %Y")
          echo "FORMATTED_DATE=${FORMATTED_DATE}" >> $GITHUB_OUTPUT

      # 6. Determine Status and Color
      - name: Determine Status and Color
        id: determine_status
        run: |
          TAG_NAME=${{ steps.extract_release.outputs.TAG_NAME }}

          STATUS="STABLE"
          COLOR="success"

          # Regex untuk menentukan status dan warna badge
          if [[ "$TAG_NAME" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            STATUS="STABLE"
            COLOR="success"
          elif [[ "$TAG_NAME" =~ ^[0-9]+\.[0-9]+\.[0-9]+-([A-Za-z]+)\.[0-9]+$ ]]; then
            LABEL=${BASH_REMATCH[1]}
            STATUS=$(echo "$LABEL" | tr '[:lower:]' '[:upper:]')
            case "$STATUS" in
              ALPHA)
                COLOR="critical"   # Merah
                ;;
              BETA|RC|HOTFIX)
                COLOR="important"  # Oranye
                ;;
              *)
                COLOR="success"    # Hijau
                ;;
            esac
          fi

          echo "STATUS=${STATUS}" >> $GITHUB_OUTPUT
          echo "COLOR=${COLOR}" >> $GITHUB_OUTPUT

      # 7. Debugging: Periksa Variabel
      - name: Check Variables
        run: |
          echo "STATUS=${{ steps.determine_status.outputs.STATUS }}"
          echo "COLOR=${{ steps.determine_status.outputs.COLOR }}"
          echo "FORMATTED_DATE=${{ steps.format_date.outputs.FORMATTED_DATE }}"

      # 8. Verify README.md Exists
      - name: Verify README.md Exists
        run: |
          if [ -f README.md ]; then
            echo "README.md ditemukan."
          else
            echo "README.md tidak ditemukan!"
            exit 1
          fi

      # 9. Replace Placeholders in README.md
      - name: Replace Placeholders in README.md
        run: |
          STATUS=${{ steps.determine_status.outputs.STATUS }}
          COLOR=${{ steps.determine_status.outputs.COLOR }}
          FORMATTED_DATE=${{ steps.format_date.outputs.FORMATTED_DATE }}

          # URL encode STATUS dan FORMATTED_DATE
          STATUS_ENC=$(printf '%s' "$STATUS" | jq -sRr @uri)
          DATE_ENC=$(printf '%s' "$FORMATTED_DATE" | jq -sRr @uri)

          # Buat URL badge
          LATEST_STATUS_BADGE_URL="https://img.shields.io/badge/LATEST%20STATUS-${STATUS_ENC}-${COLOR}?style=for-the-badge"
          LATEST_UPDATE_BADGE_URL="https://img.shields.io/badge/Latest%20Update-${DATE_ENC}-lightgrey?style=for-the-badge"

          # Debugging: Tampilkan URL yang akan dimasukkan
          echo "Latest Status Badge URL: $LATEST_STATUS_BADGE_URL"
          echo "Latest Update Badge URL: $LATEST_UPDATE_BADGE_URL"

          # Ganti placeholder di README.md langsung
          sed -i "s|___LATEST_STATUS_BADGE___|${LATEST_STATUS_BADGE_URL}|g" README.md
          sed -i "s|___LATEST_UPDATE_BADGE___|${LATEST_UPDATE_BADGE_URL}|g" README.md

      # 10. Debugging: Periksa README.md Setelah Penggantian
      - name: Debug After Replacement
        run: |
          echo "===== README.md Setelah Penggantian ====="
          cat README.md

      # 11. Commit and Push Changes
      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add README.md

          # Buat pesan commit
          COMMIT_MESSAGE="Update badges: Release=${{ steps.extract_release.outputs.TAG_NAME }}, Date=${{ steps.format_date.outputs.FORMATTED_DATE }}, Status=${{ steps.determine_status.outputs.STATUS }}"

          # Commit dan push jika ada perubahan
          git commit -m "$COMMIT_MESSAGE" || echo "No changes to commit."
          git push
