# .github/workflows/update-release-badge.yml

name: Update Release Badges

on:
  release:
    types: [published]

permissions:
  contents: write  # Memberikan izin tulis pada konten repository

jobs:
  update-badges:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Membutuhkan history lengkap untuk push

      - name: Install dependencies (Python3, jq, locales)
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip jq locales
          sudo locale-gen id_ID.UTF-8

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python packages
        run: |
          python3 -m pip install --upgrade pip

      - name: Give execute permission to Python script
        run: |
          chmod +x .github/scripts/update_badges.py

      - name: Run Update Badges Script
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: |
          python3 .github/scripts/update_badges.py