name: Update Release Badges

on:
  release:
    types: [published]

jobs:
  update-badges:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies (jq dan locales)
        run: |
          sudo apt-get update
          sudo apt-get install -y jq locales
          sudo locale-gen id_ID.UTF-8

      - name: Get Latest Release Tag & Date
        id: get_release
        run: |
          # Mendapatkan tag release terbaru
          latest_release=$(jq -r .release.tag_name < "$GITHUB_EVENT_PATH")
          echo "release=$latest_release" >> $GITHUB_OUTPUT

          # Mendapatkan published_at lalu memformat jadi "DD MMMM YYYY"
          release_date_raw=$(jq -r .release.published_at < "$GITHUB_EVENT_PATH")
          export LC_ALL=id_ID.UTF-8
          export LANG=id_ID.UTF-8
          export LANGUAGE=id_ID:en
          release_date_formatted=$(date -d "$release_date_raw" +"%d %B %Y")
          echo "release_date=$release_date_formatted" >> $GITHUB_OUTPUT

      - name: Determine Latest Status
        id: get_latest_status
        run: |
          # Regex mengekstrak label (ALPHA, BETA, dsb.) dari tag
          release=${{ steps.get_release.outputs.release }}
          regex="^[0-9]+\.[0-9]+\.[0-9]+(?:-([^.]+)\.[0-9]+)?$"

          if [[ $release =~ $regex ]]; then
            label="${BASH_REMATCH[1]}"
            if [[ -z "$label" ]]; then
              latest_status="STABLE"
            else
              latest_status=$(echo "$label" | tr '[:lower:]' '[:upper:]')
            fi
          else
            latest_status="STABLE"
          fi

          echo "latest_status=$latest_status" >> $GITHUB_OUTPUT

      - name: Update README Badges
        run: |
          # Ambil data dari step sebelumnya
          release=${{ steps.get_release.outputs.release }}
          release_date=${{ steps.get_release.outputs.release_date }}
          latest_status=${{ steps.get_latest_status.outputs.latest_status }}

          # Warna Status
          color="success"    # hijau
          [[ "$latest_status" == "ALPHA" ]] && color="critical"   # merah
          [[ "$latest_status" == "BETA" ]] && color="important"   # oranye

          # 1. Latest Release
          # Mencari:   ?include_prereleases&label=Latest%20Release&style=for-the-badge&color=informational
          # -> Pastikan di README.md cocok
          release_badge_url="https://img.shields.io/github/v/release/mohammadfirmansyah/Edvisor/$release?include_prereleases&label=Latest%20Release&style=for-the-badge&color=informational"
          sed -i "s|https://img.shields.io/github/v/release/mohammadfirmansyah/Edvisor?include_prereleases&label=Latest%20Release&style=for-the-badge&color=informational|$release_badge_url|g" README.md

          # 2. Latest Status
          # Mencari:   https://img.shields.io/badge/LATEST%20STATUS--blue?style=for-the-badge
          # -> Ada dua dash: STATUS--blue
          latest_status_badge_url="https://img.shields.io/badge/LATEST%20STATUS-$latest_status-$color?style=for-the-badge"
          sed -i "s|https://img.shields.io/badge/LATEST%20STATUS--blue?style=for-the-badge|$latest_status_badge_url|g" README.md

          # 3. Latest Update
          # Mencari:   https://img.shields.io/badge/Latest%20Update--blue?style=for-the-badge&color=lightgrey
          # -> Ada dua dash: Update--blue
          latest_update_badge_url="https://img.shields.io/badge/Latest%20Update-$release_date-blue?style=for-the-badge&color=lightgrey"
          sed -i "s|https://img.shields.io/badge/Latest%20Update--blue?style=for-the-badge&color=lightgrey|$latest_update_badge_url|g" README.md

      - name: Commit Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update badges: Release=${{ steps.get_release.outputs.release }}, Date=${{ steps.get_release.outputs.release_date }}, Status=${{ steps.get_latest_status.outputs.latest_status }}" || echo "No changes to commit"
          git push